name: Pylint

on: 
  pull_request:
    branches: "main"

jobs:
  build:
    name: Run pylint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
